apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloknative
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: $IMAGE_REPOSITORY
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: $IMAGE_PULL_SECRET_NAME
